script: "bundle exec rake spec"
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
branches:
  only:
    - master
gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/edge.gemfile
